// Generated by Ignite ignite.com/cli
import { Registry } from '@cosmjs/proto-signing'
import { IgniteClient } from "./client";
import { MissingWalletError } from "./helpers";
import { Module as IconlakeDrop, msgTypes as IconlakeDropMsgTypes } from './iconlake.drop'
import { Module as IconlakeIcon, msgTypes as IconlakeIconMsgTypes } from './iconlake.icon'

const Client = IgniteClient.plugin([
  IconlakeDrop, IconlakeIcon
]);

const registry = new Registry([
  ...IconlakeDropMsgTypes,
  ...IconlakeIconMsgTypes,
])

export {
  Client,
  registry,
  MissingWalletError
}
