version: '3'
services:
  center:
    container_name: center
    image: iconlake/center
    build: ../center
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=production
    restart: on-failure
    depends_on:
      - mongo
  service:
    container_name: service
    image: iconlake/service
    build: ../service
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    restart: on-failure
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=ABCDEFGH12345678_0
      - MONGO_INITDB_DATABASE=iconlake
      - TZ=Asia/Shanghai
    volumes:
      - ./data/mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
