version: 1
accounts:
- name: alice
  coins:
  - 200000000000000ulake
  - 20000drop
  mnemonic: maple cage treat zoo jaguar check lawn party boil orchard earn arrow immense
    win puppy mandate lion sport large total quit price found drip
- name: bob
  coins:
  - 100000000000000ulake
  - 10000drop
  mnemonic: toddler strategy valid clown sure fame jelly rescue jewel empower among
    error merit uncle hour luggage only exotic coyote hedgehog mountain armed desert
    meat
- name: faucet
  coins:
  - 100000000000000ulake
  - 50000000000drop
faucet:
  name: faucet
  coins:
  - 1000000ulake
  - 500drop
  coins_max:
  - 10000000ulake
  - 500drop
  rate_limit_window: 86400s
client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
  openapi:
    path: docs/static/openapi.yml
genesis:
  consensus_params:
    validator:
      pub_key_types:
      - ed25519
  app_state:
    bank:
      params:
        send_enabled:
          - denom: drop
            enabled: false
        default_send_enabled: true
    crisis:
      constant_fee:
        amount: "1000"
        denom: ulake
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: ulake
    mint:
      minter:
        inflation: "0.080000000000000000"
      params:
        goal_bonded: "0.670000000000000000"
        inflation_max: "0.150000000000000000"
        inflation_min: "0.060000000000000000"
        inflation_rate_change: "0.090000000000000000"
        mint_denom: ulake
    staking:
      params:
        bond_denom: ulake
validators:
- name: alice
  bonded: 100000000000000ulake
