name: Build Web

on:
  push:
    branches: [ "master", "workflow" ]
  pull_request:
    branches: [ "master", "workflow" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - run: cd service
    - run: corepack enable
    - run: pnpm run build
    - run: rm -rf ./node_modules

    - name: Upload Service
      uses: actions/upload-artifact@v4
      with:
        name: service
        path: ./service
        overwrite: true
    
    - name: Upload Center
      uses: actions/upload-artifact@v4
      with:
        name: center
        path: ./center
        overwrite: true
